from fastapi.utils.preprocess.named_entity_recognition import BiologyProcessor
from fastapi.utils.preprocess.seq2seq import TranslationProcessor
from fastapi.utils.preprocess.text_classification import MovieCommentsProcessor
